# Generated by Django 4.1.4 on 2023-01-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-publish_date']},
        ),
    ]
