# Generated by Django 4.1.4 on 2023-01-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(default='company', max_length=150),
        ),
    ]
