# Generated by Django 4.1.4 on 2023-01-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0004_alter_product_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenScent',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scents.product')),
            ],
            bases=('scents.product',),
        ),
        migrations.CreateModel(
            name='WomenScent',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scents.product')),
            ],
            bases=('scents.product',),
        ),
    ]
