# Generated by Django 4.1.4 on 2023-01-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0005_menscent_womenscent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='1.7 oz/50', max_length=150),
        ),
    ]
