# Generated by Django 4.1.4 on 2023-01-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0007_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=6),
        ),
    ]
