# Generated by Django 4.1.4 on 2023-01-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0008_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
