# Generated by Django 4.1.5 on 2023-02-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0010_remove_womenscent_product_ptr_delete_menscent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenScent',
        ),
        migrations.DeleteModel(
            name='WomenScent',
        ),
        migrations.CreateModel(
            name='MenScent',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scents.product')),
            ],
            bases=('scents.product',),
        ),
        migrations.CreateModel(
            name='WomenScent',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scents.product')),
            ],
            bases=('scents.product',),
        ),
    ]
