# Generated by Django 4.1.4 on 2023-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0012_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='womenscent',
            name='product_ptr',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='MenScent',
        ),
        migrations.DeleteModel(
            name='WomenScent',
        ),
    ]
