# Generated by Django 4.1.4 on 2023-02-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0013_remove_womenscent_product_ptr_alter_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
