# Generated by Django 4.1.4 on 2023-01-29 15:09

import creditcards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShipmentAddress', models.CharField(max_length=150)),
                ('ShipmentPhone', models.CharField(max_length=50)),
                ('CardNumber', creditcards.models.CardNumberField(max_length=25)),
                ('CardExpiry', creditcards.models.CardExpiryField()),
                ('SecurityCode', creditcards.models.SecurityCodeField(max_length=4)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
