# Generated by Django 4.1.4 on 2023-01-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetails_options_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ShipmentAddress',
            new_name='ShipAddress',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='ShipmentPhone',
            new_name='ShipPhone',
        ),
    ]
