# Generated by Django 4.1.4 on 2023-01-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_remove_payment_cardexpiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetails',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartdetails',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartDetails',
        ),
    ]
