# Generated by Django 4.1.4 on 2023-02-04 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_cartdetails_cart_remove_cartdetails_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
